language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: levonet@gmail.com
  api_key:
    secure: y7dz52sAH2wXGdvTf4ychC7kTkCmotnOVwlwStWVTomYmPKTVNE5NPdT2u+e1ylNQbl8kz9ZhHGGT64bVAsWrWTOiihGHxpAQPN1DrliCyayI2oIkjG3i7KCIE5wcAaYyD5zmyD5rRR4s8WCTwYBojLA8gkeAfGjnOt+GWAtPtglkJqRiqWqB0gkm6dZpJ22EcYXCITFSshPz8eZL94Dv7vHLsZ7mBOTSHbTwukez4V8SBQQmU398M7nQ8a2zRcM3jzZ2l53l2atAEbYj8eqXsjoIkyzuwEemh/2PWa1XrroP4f5/HJGr52SUNLlJ6CkF8KOnOtKn8FdebKDbtBgMFntGVDBrtFAFoBH+4RYb1EAeHk64Im7mcQfKPmIPyxHRHgFdJNNd7kXztqI+uye4afp+1EaEQ7CGkHtdwsV9f/7ZPvJ5BMsNh7BgQS1XmiuEvvW/GbPAKaHoPjjur4NFtJLFPGiuPA/VjsOpO+EMFxKOMYKBj3TqkXvlavuuviYInlPUF85XgYPL5mwtUsEgbHJzKDkXGck7hTvnCOGo5OflZVNs6ot8J4gJtllVJtlI7mqQN+RYbVUWDLMXXhRs3y6RxAte7HkXNeNyxiedFD9IhmXy5+79leSCxCVzy6WZ62cYba1WH15JHsyYdRtzcZ3GYxoK5IGWyDhr8SR1Ug=
  on:
    tags: true
    repo: swaggerql/swaggerql
