---
openapi: "3.0.1"
info:
  title: Demo
  version: "0.0.1"

paths:
  /test:
    get:
      summary: 1 + n
      description: |
        A custom-wrapped query

        ```sql
        SELECT 1+:n
        ```
      parameters:
      - name: n
        in: query
        description: Number
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        200:
          description: OK
  /oracle:
    get:
      summary: Test
      description: |
        SELECT
            ROUND((SYSDATE - date '1970-01-01')*24*60*60/3600)*3600 as t,
            to_date(:date, 'YYYYMMDD') + (1/24/60/60) * :timestamp,
            1 + :timestamp as a,
            :date as b,
            SYSDATE
        FROM dual
      parameters:
      - name: timestamp
        in: query
        description: Time in seconds
        required: true
        schema:
          type: integer
        example: 1569153600
      - name: date
        in: query
        description: Date
        required: true
        schema:
          type: string
        example: "19700101"
      responses:
        200:
          description: OK
